version: "3"
services:
  tracking-service-green:
    container_name: tracking-service-green
    build:
      dockerfile: Dockerfile
      context: ./TrackingService
    image: alexgim961101/tracking-service:tracking
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    restart: always

  notification-service-green:
    container_name: notification-service-green
    build:
      dockerfile: Dockerfile
      context: ./notification
    depends_on:
      - tracking-service-green
    image: alexgim961101/tracking-service:notification
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    restart: always
