spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tracking-database:3306/tracking
    username: root
    password: 3778

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
