# 워크플로의 이름 지정
name: CI

# 워크플로가 시작될 조건
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant excute permission for gradlew
        run: |
          cd notification
          chmod +x gradlew
          cd ../
          cd TrackingService
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd notification
          ./gradlew clean build
          cd ../
          cd TrackingService
          ./gradlew clean build

